# Generated by Django 5.0 on 2023-12-30 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_rename_firstname_title_artist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='SongName',
            new_name='SongNameID',
        ),
    ]
