# Generated by Django 5.0 on 2023-12-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0013_rename_songname_title_songnameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='artist_Name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='title',
            name='SongName',
            field=models.CharField(default='Unknown Song', max_length=255),
        ),
    ]
