# Generated by Django 5.0 on 2023-12-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0014_albums_artist_name_title_songname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='artist_Name',
            field=models.CharField(default='albums by:', max_length=255),
        ),
        migrations.AlterField(
            model_name='date_added',
            name='Song_Added',
            field=models.CharField(default='Input Here', max_length=255),
        ),
        migrations.AlterField(
            model_name='title',
            name='SongName',
            field=models.CharField(default='Songs by:', max_length=255),
        ),
    ]
