# Generated by Django 5.0 on 2023-12-30 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0015_alter_albums_artist_name_alter_date_added_song_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='SongNameID',
            new_name='titleID',
        ),
        migrations.AlterField(
            model_name='albums',
            name='artist_Name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='date_added',
            name='Song_Added',
            field=models.CharField(default='YourDefaultValueHere', max_length=255),
        ),
        migrations.AlterField(
            model_name='title',
            name='Artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.artist'),
        ),
        migrations.AlterField(
            model_name='title',
            name='Duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.duration'),
        ),
        migrations.AlterField(
            model_name='title',
            name='SongName',
            field=models.CharField(max_length=255),
        ),
    ]
