# Generated by Django 5.0 on 2023-12-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0016_rename_songnameid_title_titleid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='artist_Name',
        ),
        migrations.AlterField(
            model_name='date_added',
            name='date_addedName',
            field=models.CharField(default='YourDefaultValueHere', max_length=255),
        ),
        migrations.AlterField(
            model_name='title',
            name='Artist',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='title',
            name='Duration',
            field=models.CharField(max_length=50),
        ),
    ]
