# Generated by Django 5.0 on 2023-12-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0017_remove_albums_artist_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='Duration',
        ),
    ]
