# Generated by Django 5.0 on 2023-12-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0018_remove_title_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date_added',
            old_name='date_addedID',
            new_name='title_id',
        ),
    ]
